### ISSUE TITLE
Server help

### ISSUE THREAD

**Issue by IrishMassacre3** [Lebroncraft/public#18]
When I run the start server batch file, I get an error saying it's attempting a connection with missing mods and then lists every mod in the pack. It then continues to run giving errors saying things like "skipping (file)" and "trying to add (item) but item did not exist." It was working for a few minutes but then both the server and client crashed and now when I load the server and try to connect to it I can only play for about 5 seconds before the client crashes.

**Comment by censink-** [comment]
If it lists all mods in the pack, you (or whoever is trying to connect) did not copy the mods folder to either your client or server directory.
It does indeed give minor errors when starting up, that's on the mod creator's end to fix and luckily doesn't cause any problems.
The client crashes are most likely caused by a shortage in RAM, there's a small guide on how to upgrade that on the download website.

Try upgrading your RAM and let me know how it goes

**Comment by IrishMassacre3** [comment]
So i tried upgrading my RAM and that stopped the client from crashing. The server still was giving errors and shutting down. I tried completely resetting the world and downloaded new zip files for the mods (client and server) and copied all the necessary files. This worked at first then in about 15mins the server crashed. Once i brought it back up, it started giving the "attempting connection with missing mods" error again and then crashing a few minutes later.
