### ISSUE TITLE
Crash when shutting down internal server...

### ISSUE THREAD

**Issue by iAmTijl** [Lebroncraft/public#22]
When I load up or create a world, after 'creating world' it 'shuts down internal server' and crashes. 6Gigs of WAMs allocated and fairly good CPU. http://pastebin.com/R4iYGefV

**Comment by mccreeper** [comment]
same thing happens to me! it detected all 29 mods but it says shutting down internal server when i try opening a world. the forge might have an issue

**Comment by censink-** [comment]
As far as i'm aware, 'java.lang.IndexOutOfBoundsException' means it ran out of resources (most likely RAM), but since you allocated 6gb (logs confirm that) i don't think that's the real cause :/

Unfortunately i wouldn't know how to resolve this. Leaving issue opened until a solution has been found.

**Comment by iAmTijl** [comment]
It crashes when it's around 1.2 GB of RAM

**Comment by iAmTijl** [comment]
Fixed it by removing the .minecraft folder (cut it to my desktop)
