### ISSUE TITLE
Morph keybindings for non-US

### ISSUE THREAD

**Issue by Kinkyboo** [Lebroncraft/public#41]
For anyone who isn't using a US keyboard (or don't want to switch to US layout in windows because you'll miss some letters like Å for Sweden) there might be a problem using the morph menu and since there isn't any kind of in-game way to change the default behavior, I give you this:

http://pastebin.com/R4fVfEcf
Just copy-paste into iChunUtil_KeyBinds.cfg in .minecraft\config\

A numpad based keybinding solution, working as such:
(un)Favorite: NUM5
Close: ESC (Same as default)
Go Down: NUM2
Go Left: NUM4
Go Right: NUM6
Go Up: NUM8
Select Morph: NUM-Enter
Delete Morph: Shift-Delete (Delete button below Insert)

**Comment by AlastairWilkins** [comment]
Going to move your actual issue to a new issue and keep this post here, but close it and give it a custom 'tutorial' label, until we can add it to the site (if you would give us permission).
Let me know if you'd be happy for us to use this on the official site, for now, your actual issue is here: #47 

@censink

**Comment by Kinkyboo** [comment]
Sounds good to me.
